Added a more usable string type
pschachte/wybe pull request #162
Opened 2021-09-23 11:57 UTC by jimbxb

Not yet implemented: non-C-style special resources

2021-09-24 03:16 UTC, pschachte requested changes
Looks really good, just a few small changes needed.

2021-09-24 03:16 UTC, pschachte commented on wybelibs/wybe/control.wybe
> +pub def {terminal,semipure} error(message:c_string) use call_source_location {
There should be a Wybe string version of error.

2021-09-24 03:16 UTC, pschachte commented on wybelibs/wybe/string.wybe
> +          | concat(left:_, r:_)
Please rename `r` to `right`

2021-09-24 03:27 UTC, jimbxb commented on wybelibs/wybe/control.wybe
> +pub def {terminal,semipure} error(message:c_string) use call_source_location {
I agree with this. 

However, I have tried to implement this via the following
```
pub def {terminal,semipure} error(message:string) use call_source_location {
    foreign c {terminal,semipure} error_exit(call_source_location, c_string(message))
}
```
And received this error message: 
```
wybelibs/wybe/control.wybe:14:68: error has normal (total) determinism, but declared terminal
```

It appears there is some underlying issue with determinism checks of terminal procedures. Yet to try to diagnose further

2021-09-26 11:54 UTC, pschachte approved these changes

2021-09-26 12:21 UTC, pschachte commented
Uggg!  There are conflicts in four .exp files because of the change I just committed for resources.  Could you please re-run ./update-exp and commit the changes to this PR, so I can merge it?

2021-09-26 12:22 UTC, jimbxb commented
On it now. 

Looks like string now needs to import `wybe.phantom`, which wasn't the case before when importing `io`

2021-09-26 12:59 UTC, pschachte approved these changes

2021-09-26 12:59 UTC, merged