Higher Order
pschachte/wybe pull request #240
Opened 2021-12-22 11:31 UTC by jimbxb

This PR is a tentative PR for higher order in Wybe.

A few things need to be ironed out still (resourceful tests, namely).

I'm sure there are some bugs/issues. I also have not documented a lot fo the code I have written/updated the docs. That will come in time.

2021-12-30 23:15 UTC, pschachte requested changes
Unfortunately, the recently merged PRs have created a few conflicts for this PR.  Could you please resolve them?  Then I'll tackle this PR.  I won't merge anything else until I've handled this PR, at least for a week or so.

2021-12-31 00:17 UTC, jimbxb commented
I'm working on patching it up now. I made a slight error in the resource promotion/demotion semantics that I want to fix also.

2022-01-31 08:24 UTC, pschachte requested changes
Mostly good.  The two biggest issues is that it would be wrong to remove the globals arguments from LPVM code.  It's crucial to keep LPVM code semantics pure for some of the analyses and transformations we want to apply.  And, of course, the WYBE.md file needs to be updated to document how HO programming works, and also to document the new LPVM instructions.

2022-01-31 08:24 UTC, pschachte commented on src/AST.hs
> -                 | GlobalArg       -- ^An arguemtn to pass globals
We definitely need to pass the globals argument in and out of LPVM procs, to ensure the semantics is declarative.  What `ArgFlowType` will these arguments have?

2022-01-31 08:54 UTC, jimbxb commented
The reason I removed the globals arguments was twofold. 

First, i believe we can rely on the `GlobalFlows` for call omissions/reording -- if a call has no global out flows then we can omit it (assuming it's pure and has no other outs); if a two calls have no intersecting global flows then we can freely reorder them (assuming nothing else is causing us to be unable to reorder them). 

The `#globals` argument also handled this, however it was tedious to omit a call if this argument was around because the global in/out had to be moved -- removing the argument removed this requirement and so made the handling of this argument much cleaner (as I didn't need to move it). 

It also impedes reordering. If we have two calls that use different globals, there's no reason we can't reorder them-- if we have the globals arguement we can't without also swapping some arguments.

The other reason was the LPVM `void` instructions I had to introduce-- I think now with better global flow analysis I don't need it, but I'm not overly confident there as this is a new idea I had.

If something isn't quite right with my arguments here it should be easy to add the globals arg back in.

2022-01-31 08:55 UTC, jimbxb commented
I'll work on cleaning up the rest of the code/writing docs very soon. Glad there wasn't anything else *too* major :)

2022-01-31 09:49 UTC, jimbxb commented on src/Resources.hs
> +transformProcGlobals :: ProcDef -> Int -> Compiler ProcDef
The context where this is used in `Builder` requires the `Int` arguement

2022-01-31 09:49 UTC, jimbxb commented on src/Resources.hs
> +-- usage to appear as though it obeys uniquness checking
I have not investigated the effects on either, Perhaps this could be an issue, so I will document it

2022-01-31 11:11 UTC, jimbxb commented on src/Types.hs
>  testToBoolFn _ = Nothing
The HO call info does not handle this information

2022-01-31 11:17 UTC, jimbxb commented on src/Flatten.hs
> +                               Unplaced $ Var resultName ParamOut Ordinary])
Ah! Thats the intended purpose of implicit... I was unware of this and just removed it because it was unused

2022-01-31 11:18 UTC, jimbxb commented on src/Types.hs
>  boolFnToTest _ = Nothing
As above

2022-02-21 06:58 UTC, pschachte requested changes
Just a few small changes to be made, mostly to `WYBE.md`.

2022-02-21 06:58 UTC, pschachte commented on src/AST.hs
> +-- |Replace a Prim's GlobalFlows with new GlobalFlows
Ah, I see.  The more we are able to ignore the difference between global flows and normal arguments, the easier it will be for code that doesn't care about the difference, such as analyses.  If it makes sense where this fn is used, it might be better to merge the the `replace*` functions.

2022-02-21 06:58 UTC, pschachte commented on src/Resources.hs
> +
Nice!

2022-02-21 06:58 UTC, pschachte commented on src/Resources.hs
> +-- usage to appear as though it obeys uniquness checking
OK, then, please try those to see if they are problems, and if so add issues for them.

2022-02-21 06:58 UTC, pschachte commented on src/Types.hs
>  testToBoolFn _ = Nothing
Isn't that a bug?  It should be possible to pass a test proc with no outputs where a Boolean-valued function is expected.  If that's not handled, please add an issue for it.

2022-02-21 22:23 UTC, jimbxb commented on WYBE.md
> +closed variables inside the body of an anonymous procedure is *not* reflected
I opted to allow this because you can "re-assign" an input to a procedure as in what follows:

```
def foo(a:int) {
    ?a = 1
}
```

I wanted to emulate regular procedures as closely as follows, so making this an error feels odd to me. Happy to fix this if need be in a bugfix PR

2022-02-21 22:39 UTC, jimbxb commented on src/AST.hs
> +-- |Replace a Prim's GlobalFlows with new GlobalFlows
This function is only ever used to replace the arguments of a function after marked as being the last use of a variable or when we canonicalise a proc with inputs only. In the later case, procedures should have global flows.

I don't think it makes sense here to merge the `replace*` functions.

2022-02-21 23:51 UTC, jimbxb commented on src/Types.hs
>  testToBoolFn _ = Nothing
This is handled, just separately

2022-02-24 07:43 UTC, pschachte approved these changes

2022-02-24 07:44 UTC, pschachte commented
Closes #36

2022-02-24 08:38 UTC, merged