Infer more LLVM types during codegen, remove some unused code
pschachte/wybe pull request #273
Opened 2022-04-04 12:44 UTC by neon64

I haven't had a chance to discuss this one yet, so I'd be open to any feedback (maybe there's something I'm missing why it's done the way it is?)

- When implementing new LPVM instructions, I accidentally introduced a couple of bugs by falsely claiming an operand was of type `x` (by writing `assign name op x`), when the operand was actually of a different type `y`.
- I learned that each LLVM `Operand` has a type, which can be retrieved with `typeOf operand`

Thus, I thought it might make sense to use the LLVM type of the operand itself, rather than passing in an extra argument. This also simplifies `doCast` and `consCast`.

I believe this code change shouldn't break any of the tests / final dumps. I'd be keen to hear what you think.

I also have an extra commit https://github.com/neon64/wybe/commit/dacb26958184579b1df9d221864e6118c80ba0c6 which removes all the `getelementptr i64, i64* %xyz, i64 0` instructions from `gcAccess` and `gcMutate` which afaik are just nops (I guess they get optimized out by LLVM pretty quickly, but it seemed a bit redundant to generate them in the first place). However, this change breaks nearly every single final-dump test, so I thought I'd keep it out of this PR for now.

2022-04-04 12:47 UTC, neon64 commented on test-cases/final-dump-test.sh
> +	ed -s $out <<< w > /dev/null 2>&1 || abort "failed to add newline to output, is ed installed?"
I realised that this is why the tests were failing locally last week - I didn't have `ed` installed so it silently failed to add newlines.

I added this as wasn't sure if someone in the future might encounter the same issue? Alternatively I could add a note in [INSTALL.md](https://github.com/pschachte/wybe/blob/master/INSTALL.md) rather than modifying this script?

2022-04-04 13:15 UTC, jimbxb reviewed
Thanks for the help cleaning up the LLVM codegen. It's not the nicest file to trawl through.

I'd actually encountered this myself when dealing with higher order tests (as the Boolean would be an `i64` and LLVM didn't like that without a `trunc`, and this is why the `castVar` function is now called in a fork). A lot of this code was written before the type system even had generics, to my knowledge, so there's probably a fair few legacy decisions that still exist.

2022-04-04 13:15 UTC, jimbxb commented on src/Codegen.hs
> +         stVars :: Map.Map String (Operand,LLVM.AST.Type)
Do we still need to store the `Type` here? Can't we just use `typeOf` to get the same information?

2022-04-04 13:16 UTC, jimbxb commented on test-cases/final-dump-test.sh
> +	ed -s $out <<< w > /dev/null 2>&1 || abort "failed to add newline to output, is ed installed?"
What good is a Unix environment if there's no `ed` installed :(

Probably a good thing to note in INSTALL, but only as something required for tests--something a user wouldn't really be doing

2022-04-05 12:52 UTC, neon64 commented on src/Codegen.hs
> +         stVars :: Map.Map String (Operand,LLVM.AST.Type)
good point, I've update the PR to remove that

2022-04-06 07:41 UTC, jimbxb commented on test-cases/final-dump-test.sh
> +	ed -s $out <<< w > /dev/null 2>&1 || abort "failed to add newline to output, is ed installed?"
Scouring SO I have found [this](https://unix.stackexchange.com/a/263965):
```
[ -n "$(tail -c1 file)" ] && echo >> file
```
The poster claims this is POSIX compliant, and also works without `ed` :)

2022-04-07 04:46 UTC, pschachte requested changes
Just one change to reverse, otherwise it's all good.

2022-04-07 04:46 UTC, pschachte commented on src/Codegen.hs
> --- Helpers for allocating, storing, loading
You should probably keep this.  I'm sure we're going to want it eventually, and you're probably going to need it for your project.

2022-04-11 03:19 UTC, neon64 commented on src/Codegen.hs
> --- Helpers for allocating, storing, loading
no worries, I've added it back in again

2022-04-11 04:51 UTC, pschachte approved these changes

2022-04-11 04:51 UTC, merged