Implement last call modulo construction optimization
pschachte/wybe pull request #279
Opened 2022-04-18 14:26 UTC by neon64

The branch I've been playing around with for the last month or so is finally beginning to converge to something usable, so I thought I should put up this PR to discuss some of questions directly related to the implementation, and also gather some feedback.

### Missing pieces

- this branch fails a few tests. I have had a look through `ERRS` and I believe all the differences are expected, i.e.: they are a result of this optimization kicking in and therefore affecting the final dump LPVM/LLVM. I'm not sure the best way to easily show/summarize this though.

- I haven't updated [WYBE.md](/pschachte/wybe/blob/master/wybe.md) yet, with e.g.:  details of what how `outByReference` flow should work

### Implementation notes (since last meeting)

The main guts of this PR are probably 50/50 between `src/LastCallAnalysis.hs` for the LPVM transformation, and `src/Blocks.hs` for the codegen changes. For this MVP version I only handle the case of directly recursive functions, and don't hook into multiple-specialization at all.

The last call analysis pass (added to `src/Builder.hs`) currently runs *before* all the specialized versions get generated (in `multiSpeczTopDownPass`). This was the cause of "empty function bodies" bug I mentioned earlier, i.e.: specialized function bodies looking something like this:

```
Blocks: nrev<0>[somemultispeczid](lst##0:generic_list(T),  outByReference #result##0:generic_list(T))<{}; {}>
Blocks:     foreign llvm icmp_ne(lst##0:wybe.int, 0:wybe.int, ?tmp#8##0:wybe.bool)
Blocks:     case ~tmp#8##0:wybe.bool of
Blocks:     0:
Blocks:
Blocks:     1:
```

I did some debugging and I believe it was because the analysis only considered `FlowOut` params as outputs, so it thought the whole function body had no outputs (i.e.: after turning on `-l BodyBuilder`, the list of `outSubsts` was always empty), therefore removed every prim since they "weren't needed". I believe there are two possible solutions for this, either I could move LastCallAnalysis to after specialized versions are generated, or I make the other passes handle post-LastCallAnalysis proc bodies. I tried the latter option, and made a couple of changes to `src/Transform.hs` to treat the `FlowOutByReference` flow the same as a `FlowOut` flow. This nearly worked, except it didn't like the inverted ordering of mutates before the tail call:

```prolog
foreign lpvm mutate(~tmp#10##0:wybe.list(T), ?result##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, takeReference tail##0:wybe.list(T)) @list:8:27
tail append.append<0>[410bae77d3](~t##0:wybe.list(wybe.int), ~back##0:wybe.list(wybe.int), outByReference ~tail##0:wybe.list(wybe.int)) #1 @append:7:13
```

In the specialized body, the final call `tail append.append<0>[410bae77d3]` was simply missing. I believe this was since BodyBuilder saw `outByReference ~tail##0:wybe.list(wybe.int))` as being created right at the end, but never used after (not in `usedLater`). To be honest, this BodyBuilder code was starting to be way out of my depth, and I wasn't sure it was a good idea to fundamentally change how it analyses LPVM. Thus, I instead made a change to `LastCallAnalysis.hs` to keep the final "mutates-that-actually-calculate-addresses" after the tail call, e.g.: 

```prolog
foreign lpvm alloc(16:wybe.int, ?tmp#8##0:generic_list(T)) @generic_list:nn:nn
foreign lpvm mutate(~tmp#8##0:generic_list(T), ?tmp#9##0:generic_list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~h##0:T) @generic_list:nn:nn
tail generic_list.append<0>(~t##0:generic_list(T), ~y##0:generic_list(T), outByReference tmp#2##0:generic_list(T)) #1 @generic_list:nn:nn
foreign lpvm mutate(~tmp#9##0:generic_list(T), ?#result##0:generic_list(T), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~takeReference tmp#2##0:generic_list(T)) @generic_list:nn:nn
```

It was then relatively straightforward to modify `src/Blocks.hs` to pick up that any Prims after a call marked with a new `tail` LPVM attribute must be *"mutates-that-actually-calculate-addresses"*, and so calculate the addresses *before* making the call. This also means that the fourth flow, `FlowTakeReference`, is superfluous as one can infer that any `mutate()` after a call marked with `tail` must necessarily have a `takeReference` final arg. I wonder then, is it overkill to introduce an entirely new flow which is only ever used in the last argument of a `mutate()` call? On the other hand, there is a nice symmetry between `outByReference` and `takeReference`.

### Types in codegen

In my first implementation of this optimisation (the "explicit version" - [at this commit](https://github.com/pschachte/wybe/blob/bfa0baa8d563f282de7d14c30a30253d087bd754/src/LastCallAnalysis.hs)), I added new a new `Pointer` `TypeRepresentation` which was used by `outByReference` parameters. I now agree that that isn't a good approach for LPVM, and so now codegen takes a more implicit approach, where it looks at the both the wybe type, and `PrimFlow` of a parameter, in order to decide which LLVM type it should use. If flow is `FlowOutByReference` or `FlowTakeReference`, then actual LLVM type is `ptr_t originalType`.

There is also a concept of a "shadow reference variable". When calling a function with an `outByReference` parameter, if we don't have an existing address to store the output, codegen will instead stack-allocate space for said output, and pass this "shadow reference variable" (`%65` in the example below), and then load the actual value afterwards (into `%66` below).

```
Blocks:   %65 = alloca i64
Blocks:    call fastcc  void  @"append.append<0>[410bae77d3]"(i64  %27, i64  %59, i64*  %65)
Blocks:   %66 = load  i64, i64* %65
```

I call this a "shadow" variable since it is internal to codegen. The LPVM code only cares about the underlying value - i.e.: given the LPVM below, there is no way to access or see the shadow var `x3#ref##0` that codegen creates internally just before the call to append.

```prolog
foreign lpvm mutate(~tmp#40##0:wybe.list(T), ?tmp#41##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 5:T) @list:8:27
foreign lpvm mutate(~tmp#41##0:wybe.list(T), ?tmp#5##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#6##0:wybe.list(T)) @list:8:27
append.append<0>[410bae77d3](~tmp#0##0:wybe.list(wybe.int), tmp#5##0:wybe.list(wybe.int), outByReference x3##0:wybe.list(wybe.int)) #10 @append:21:1
wybe.io.print_list<0>(~tmp#5##0:wybe.list(wybe.int))<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #11 @append:23:2
wybe.io.print_list<0>(~x3##0:wybe.list(wybe.int))<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #12 @append:24:2\
```

### Summary

Oops, there is a lot to go through here! I've tried my best to articulate some of the things I've encountered over the last week in writing, but would be more than happy to talk through them in this week's meeting, using this very-long PR description as summary notes.

2022-04-18 14:39 UTC, neon64 commented on src/Blocks.hs
> +getTailCallHint attrs args outTy =
...and as if my PR description wasn't long enough, I have some more interesting things I discovered this weekend. :smile: 

It turns out just blindly adding `tail` to every LLVM call can trigger some Very Bad Behaviour in LLVM.

For example, consider this `wybemk` output after being passed through LLVM's optimizer:
https://godbolt.org/z/GrcWv65qs

Note that a `load` has disappeared and an `undef` has crept in. That is why my append test program printed `[0]` in `-O3` and `[1,2,3,4,5,6]` in `-O1`. At first I naively thought this could be an LLVM bug. But it turns out LLVM's language reference has this to say about the `tail` attribute:

![2022-04-16T23:20:05,323375165+10:00](https://user-images.githubusercontent.com/7961339/163823141-1dd08857-fde3-4d84-ad75-12c16ffd9198.png)

So in this case, since my optimisation now starts adding `allocas` in some places, we are producing Bad IR<sup>TM</sup> and so LLVM is free to do what it wants.
 
My slightly solution thus far is to be more careful when we mark calls with `tail` (and now also `musttail`) LLVM attributes. My suggested implementation looks at both the presence of the `tail` LPVM attribute (which is effectively a promise that the callee don't use any allocas from the caller*), and also the signature of the callee, to infer a `TailCallKind` which may be slightly conservative, but hopefully won't break LLVM.

*`LastCallAnalysis.hs` is the only place which adds this `tail` LPVM attribute to LPVM calls, and it should guarantee this promise

2022-04-20 02:21 UTC, pschachte commented on src/Blocks.hs
> +getTailCallHint attrs args outTy =
There's a script update-exp in the top-level directory that runs all tests and does a colourised word diff between the actual and expected outputs, and asks whether the new output is what should be expected, and if so, replaces the expected output file with the new one.  The colourised word diff makes it a lot easier to see what's actually different compared to the ERRS file, although it's still laborious.  If you go through all the differences and you can mark all of them correct, and push the changes to the .exp files, then the PR will pass all tests.

If you haven't made the new flows user-visible, then there is probably not much need for documentation changes.  At some point, there should probably be a section toward the end of the doc that talks about efficiency and how to write Wybe code to be as efficient as possible, which would be the place to document your change, but that doesn't exist yet.

There's a function `flowsOut` defined in AST.hs that works for `FlowDirections`, which is the Wybe source code version of `PrimFlow`.  Since it's no longer correct to just pattern match against `FlowOut` to check if a `PrimFlow` is an output, you should define a function `primFlowsOut` in AST.hs that returns `True` for both `FlowOut` and `OutByReference` flows, and use that to decide if a proc produces any outputs.  It's probably worth grepping the code for FlowOut and see if there are any other places that need to use the new `primFlowsOut` function.

OK, it's fair enough to keep the mutate instruction at the end, and somehow mark it to indicate that instead of doing it, the LLVM generation should take the address of the memory it would have mutated.  The tricky thing about doing it that way is that you have to generate LLVM code for the mutate instruction before generating code for the preceding call.

Yes, BodyBuilder does get pretty subtle.  I'm not sure we'll be able to get away with keeping it ignorant of the OutByReference flow in the long run, but we can certainly try.

Nice catch about the LLVM handling of tail calls.  I didn't realise that restriction existed, although on reflection I should have.  Your solution of not marking non-tail calls as tail calls sounds like the right one.

2022-05-03 06:25 UTC, jimbxb requested changes

2022-05-03 06:25 UTC, jimbxb commented on src/LastCallAnalysis.hs
> +lastCallAnalyseProc def = do
When I introduced closures, I added a field in `ProcDef`s that dictaty the variant of a procedure, which says if the proc is a constructor, deconstructor, etc. The really important one is the `Closure` variant, that is applied in the case the procedure originates from a closure in the code--either a partial application of some other proc or an anonymous procedure. 

I think you should not apply this analysis to such Closure procedures. These closure procedures have a very particular interface in the LLVM generation, and this analysis may violate that. I am unsure if this can occur, but a defensive check is quite cheap and simple to implement, so should be no harm

2022-05-04 06:47 UTC, pschachte commented on src/LastCallAnalysis.hs
> +lastCallAnalyseProc def = do
It may be necessary to do that transformation on closure procedures.  If the proc you're closing over has an out-by-reference argument, it's necessary to allocate a stack slot, pass its address to the proc, and then fetch the value out of the stack slot.  You're right that we don't want to transform a closure proc to change its parameter passing, but for the moment we only do that for recursive procs, and closure procs won't be recursive, so that shouldn't be a problem.  But it couldn't hurt to put in a test to forever rule out changing the flow direction of a closure proc.

2022-05-05 00:01 UTC, neon64 commented on src/LastCallAnalysis.hs
> +lastCallAnalyseProc def = do
thanks for looking at this @jimbxb , it's been on my todo list to see how this optimization interacts with higher-order procs. Maybe I will try and find a test-case where this could be a problem

2022-05-06 05:21 UTC, neon64 commented on test-cases/final-dump/higher_order_append.exp
> +  %94 = load  i64, i64* %93
I have added this test-case to ensure that we call the last-call-optimised version of functions (e.g.: append) inside of closure procs (note the `alloca` and then `load` immediately after)

2022-05-06 05:24 UTC, neon64 commented on src/LastCallAnalysis.hs
> +            return def
have explicitly skipped transforming closure procs for now, even though they should never be directly tail recursive so should never be eligible for transformation

2022-05-06 05:24 UTC, jimbxb commented on test-cases/final-dump/higher_order_append.exp
> +  %94 = load  i64, i64* %93
Great. Looks okay by me

2022-05-06 05:32 UTC, neon64 commented on wybelibs/wybe/list.wybe
> +use wybe.io, wybe.string, wybe.c_string, wybe.char, wybe.range, wybe.phantom, wybe.count, wybe.float
I had some trouble implementing `print` for lists and lists of lists, but am not sure if its a compiler bug or just me being silly. First problem: the compiler complained these types were unknown, until I added all of these imports

```
./wybemk --force-all -L wybelibs wybelibs/wybe.o
Error detected during type checking of module(s) wybe, wybe.array, wybe.array.raw_array, wybe.control, wybe.string, wybe.io, wybe.list, wybe.range, wybe.machine_word
In proc declaration, unknown type wybe.char
In proc declaration, unknown type wybe.phantom
In proc declaration, unknown type wybe.count
In proc declaration, unknown type wybe.float
In proc declaration, unknown type wybe.string
make: *** [Makefile:52: wybelibs/wybe.o] Error 1
```

2022-05-06 05:32 UTC, neon64 commented on wybelibs/wybe/list.wybe
> +pub def print(xs:list(list(int))) use !io {
The compiler also wasn't happy when I had this overload (for `list(list(int))`) in the `wybe.io` module. I saw https://github.com/pschachte/wybe/pull/287/files though, so I have just put these in `wybe.list` from the get-go for now.

```
./wybemk --force-all -L wybelibs wybelibs/wybe.o
Error detected during type checking of module(s) wybe, wybe.array, wybe.array.raw_array, wybe.control, wybe.string, wybe.io, wybe.range, wybe.machine_word
In proc declaration, unknown type wybe.list(wybe.int)
In proc declaration, unknown type wybe.list(wybe.list(wybe.int))
make: *** [Makefile:52: wybelibs/wybe.o] Error 1
```

2022-05-06 05:34 UTC, jimbxb commented on wybelibs/wybe/list.wybe
> +use wybe.io, wybe.string, wybe.c_string, wybe.char, wybe.range, wybe.phantom, wybe.count, wybe.float
This occurs because of the `pragma no_standard_library`. You need to add all of the imports for each of the types as theyre not public imports in `io`... I think this is a bug tbh

2022-05-06 05:41 UTC, jimbxb commented on wybelibs/wybe/list.wybe
> +pub def print(xs:list(list(int))) use !io {
Same deal here. `io` doesnt know about `wybe.list`--it shouldnt need to

2022-05-06 05:48 UTC, neon64 commented on wybelibs/wybe/list.wybe
> +pub def print(xs:list(list(int))) use !io {
To clarify this one: I did add "use wybe.list" at the top of io.wybe and it still didn't work. But it only started complaining once I added the "list(list(int))" overload ("list(int)" was working fine as of a few commits ago). To me it seems like the typechecker doesn't like how the type parameter refers to the type itself? (i.e.: T=list(T'), T' = int)

2022-05-08 23:57 UTC, pschachte requested changes
This looks good, except that I merged another PR that conflicts with this.  That was James's PR moving the print procs into the modules for what they were printing.  Unfortunately, that make widespread but trivial changes to the .exp files.  Could you please update this PR to fix the merge conflicts and let me know when it's ready, and I'll merge it?

2022-05-08 23:57 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +pub def print(xs:list(list(int))) use !io {
Please, when you have time, try to replicate this in a minimal test case and file a bug report.

2022-05-09 12:58 UTC, neon64 commented on wybelibs/wybe/io.wybe
> +use wybe.list
ah no it isn't, looks like I made a commit locally to remove it, but forgot to push the branch. Will update

2022-05-09 23:39 UTC, neon64 commented on wybelibs/wybe/list.wybe
> +pub def print(x:list(int)) use !io {
okay I've attempted that in https://github.com/pschachte/wybe/pull/279/commits/8ba5099fcf91cae8cf38c53f4b6785e49462e388#diff-5430fa35f7b4236a1975f749ce16b553cae9ea6fad20736b2c73529d27813f7f

2022-05-09 23:41 UTC, neon64 commented
I merged in latest changes and got tests passing again. And I've put on my todo list to replicate/file a bug report for https://github.com/pschachte/wybe/pull/279#discussion_r867558363

2022-05-11 01:16 UTC, pschachte approved these changes

2022-05-11 01:16 UTC, merged