Fix for #300
pschachte/wybe pull request #303
Opened 2022-05-20 01:52 UTC by jimbxb

2022-05-20 06:10 UTC, pschachte requested changes

2022-05-20 06:10 UTC, pschachte commented on src/Types.hs
> +lookupTyped :: String -> OptPos -> TypeSpec -> Typed TypeSpec
Could you add a bit of doc?  The name is a bit mysterious to me.

2022-05-20 06:10 UTC, pschachte commented on test-cases/final-dump/unexported_type_overload.wybe
> +    pub def proc(x:hidden) { pass }
I thought this PR was meant to give an error message in this case?

2022-05-20 06:21 UTC, jimbxb commented on test-cases/final-dump/unexported_type_overload.wybe
> +    pub def proc(x:hidden) { pass }
Yeah, so all this PR does is remove a spurious error.

As there is a correct overload (the `char` one), all is okay with no error.

I can add a test case to show the error is reported if the overload fails

2022-05-20 06:35 UTC, jimbxb commented on test-cases/final-dump/unexported_type_overload.wybe
> +    pub def proc(x:hidden) { pass }
Nevermind, I found a way. Its a hack and a half around the type system though..

2022-05-22 06:16 UTC, pschachte approved these changes

2022-05-22 06:16 UTC, merged