Stdlib additions/tweaks
pschachte/wybe pull request #306
Opened 2022-05-21 11:55 UTC by jimbxb

* Added `null` test for lists
* Re-ordered `list.print` arguments, regarding discussion in #304

2022-05-22 07:28 UTC, pschachte requested changes
Nits.

2022-05-22 07:28 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +pub def {test} null(xs:_(T)) {
I think a better name for this would be `empty`.  It really should be defined as:
```
pub def empty:_(T) = []
```
but it won't work because = doesn't work for generic types.   Grumble.

2022-05-22 07:28 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +# Helper for length
Actually, it's a helper for reverse

2022-05-22 07:28 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +# Map a procedure over two lists, producing a third of the results
Pretty unclear; this leaves me wondering what happens to the other 2/3 of the results.

2022-05-22 07:28 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +# foldl(f, [a1, a2, ..., aN], !b) ~ f(a1, !b); f(a2, !b); ...; f(aN, !b)
Nice!

2022-05-22 07:28 UTC, pschachte commented on wybelibs/wybe/list.wybe
> +# Foldl
Filter

2022-05-22 07:29 UTC, jimbxb commented on wybelibs/wybe/list.wybe
> +# Map a procedure over two lists, producing a third of the results
I didn't read it that way. Will update.

2022-05-22 07:30 UTC, jimbxb commented on wybelibs/wybe/list.wybe
> +# Foldl
Oops. I should copy-paste less.

2022-05-22 07:43 UTC, jimbxb commented
Picked.

2022-05-27 23:37 UTC, pschachte approved these changes

2022-05-27 23:37 UTC, merged