Added warning when type constraint is of the current type
pschachte/wybe pull request #351
Opened 2022-08-07 04:19 UTC by jimbxb

Fixes #135

2022-08-08 03:43 UTC, pschachte requested changes
This is nice work, and has the pleasant side effect of giving better source positions in unrelated errors.  But there are a few spurious warning messages.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/loop_bug.exp
> +[93mfinal-dump/loop_bug.wybe:1:31: Explicit specification of current type int_list,
This warning looks erroneous.  It points to the `cons` constructor.  The second warning points to the tail member, which should be warned about, but the constructor should not be.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/generic_use.exp
> +[0m[93mfinal-dump/generic_list.wybe:4:9: Explicit specification of current type generic_list(T),
The `generic_list` type name doesn't appear on lines 4 or 5, so these warnings are spurious.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:1:27: Explicit specification of current type generic_list(T),
Column 27 is the `cons` constructor, which doesn't explicitly mention the type name.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:3:5: Explicit specification of current type generic_list(T),
Column 5 is the def keyword. Presumably this refers to the return type of append; in this case, it should probably reference column 9, which is the function name. Ideally the warning would explicitly mention that it refers to the function return type, if that's not too hard.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:4:9: Explicit specification of current type generic_list(T),
Lines 4 and 5 don't mention the type name at all so there shouldn't be any warnings for those lines.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/generic_list.exp
> +[93mExplicit specification of current type generic_list(T),
This warning doesn't have a line number, so I'm not sure what it refers to.

2022-08-08 03:43 UTC, pschachte commented on test-cases/final-dump/type_int.exp
> +[0m[93mfinal-dump/type_int.wybe:2:42: Explicit specification of current type myint,
Column 42 is the `foreign` call, which doesn't explicitly specify the type anywhere.

2022-08-08 04:18 UTC, jimbxb commented
Yep, the issues arise where I'm using the wrong source POS. I'll fix it up soon (I hope)

2022-08-08 06:32 UTC, jimbxb commented on test-cases/final-dump/loop_bug.exp
> +[93mfinal-dump/loop_bug.wybe:1:31: Explicit specification of current type int_list,
The warning occurs because the field `tail` has been given an explicit type, and this type is propagated into the (de)constructor.

2022-08-08 06:37 UTC, jimbxb commented on test-cases/final-dump/generic_use.exp
> +[0m[93mfinal-dump/generic_list.wybe:4:9: Explicit specification of current type generic_list(T),
I believe these once come from the transformation of a `FuncDecl` into a `ProcDecl` with an explicitly typed `move`. I can get rid of those,

2022-08-08 06:38 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:1:27: Explicit specification of current type generic_list(T),
As per previous comment, the field does.

2022-08-08 06:39 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:4:9: Explicit specification of current type generic_list(T),
See `generic_use`.

2022-08-08 06:39 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[93mExplicit specification of current type generic_list(T),
Grumble. Will dig into this

2022-08-08 06:41 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[93mExplicit specification of current type generic_list(T),
Ah, there was an `Unplaced` in the aforementioned `move`!

2022-08-08 06:43 UTC, jimbxb commented on test-cases/final-dump/type_int.exp
> +[0m[93mfinal-dump/type_int.wybe:2:42: Explicit specification of current type myint,
This looks to be fixed with the `FuncDecl` `move` typing.

2022-08-08 06:43 UTC, pschachte commented on test-cases/final-dump/loop_bug.exp
> +[93mfinal-dump/loop_bug.wybe:1:31: Explicit specification of current type int_list,
If we just didn't issue this warning at all for generated accessor/mutator/deconstructor/equality procs/funcs (but do warn for generated constructor procs), would that eliminate any needed warnings?  In this case, you'd get a warning for the constructor, so the one for the deconstructor is redundant.  And you recently added information noting which procs are generated, so it should be possible.

2022-08-08 06:50 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:3:5: Explicit specification of current type generic_list(T),
I think this one requires a tweak of the parser. The position is grabbed from the `"def"` keyword, but I can get it from where the `"def"` token ends easily.

2022-08-08 07:48 UTC, jimbxb commented on test-cases/final-dump/generic_list.exp
> +[0m[93mfinal-dump/generic_list.wybe:3:5: Explicit specification of current type generic_list(T),
As for changing the message I think that'll be a bit more work, as I'd have to special case this one. I am not sure it is work it.

2022-08-11 06:31 UTC, pschachte approved these changes

2022-08-11 06:31 UTC, merged