Added foreign proc def
pschachte/wybe pull request #371
Opened 2022-12-30 03:32 UTC by jimbxb

Closes #366

2023-01-29 09:25 UTC, jimbxb commented
This is unfinished. I'd like to make it such that the order of which resources are specified is the order they're passed to the foreign proc. I think I can also make the parsing a little cleaner.

2023-01-31 00:18 UTC, pschachte commented
If we want this to be fairly general (ie, able to interface to pretty much any C function), then it's not just the order of resources that needs to be flexible.  It should also be possible to interleave the resources among the positional parameters in any order.  Also, we should probably support pass by reference for outputs.  Perhaps a Wybe in/out parameter should to translated to a single pass-by-reference C parameter.

But maybe it's better to handle the simple cases first, and extend it in later PRs as time and inspiration dictate.

2023-01-31 01:36 UTC, jimbxb commented
Interleaving can just be done in the verbose way, like:

```
def foreign c interleave(x) use !foo {
    foreign c interleave(foo, x, ?foo)
}
```

Now that I think about it, we should probably require parameters have their types specified because there's no way of inferring them :)

2023-04-09 12:24 UTC, jimbxb commented
Converting to draft while I havent made the relevant changes required.

2024-10-02 04:35 UTC, pschachte requested changes
This looks great.  I just have one issue with it:  conceptually, the resources used by a proc should be thought of as a set.  In the case of foreign calls, they must be ordered, with duplication respected, as you've done.  So the WYBE.md file should mention that, in foreign definitions only, order is significant, and resource names can be repeated (and an in-out resource can be separated into an in one and an out one).  Can you please update the doc to say all that?

There's also an issue with how multiple outputs are handled.  This isn't supported by C, but we could actually handle it the way C does now, using `FlowOutByReference` arguments (ie, passing a pointer to where to write the output).  But we can leave this as future work.

One concern I do have, though, is that we continue to treat resources in non-foreign procs as if they were sets, so they should be sorted and duplicates removed, and a separated in and out resource should be coalesced into a single in-out resource.  I didn't notice that happening in the code, but I may have overlooked it.  If you haven't done that, could you please do so?

Another would-be-nice thing would be to use this functionality for all foreign functions used in the library, but again that can be a separate PR.

2024-10-02 04:43 UTC, jimbxb commented
I can do the doc updates.

On coalescing resources, I think this step might not be done yet. It should go into the normalisation phase of resources, which happens just before type checking. I'll double check and fix it up if not.

2024-10-03 01:29 UTC, pschachte approved these changes
Excellent, thanks for that!

2024-10-03 01:29 UTC, merged