Incorporate parameter information into global flows
pschachte/wybe pull request #377
Opened 2023-02-04 04:15 UTC by jimbxb

Closes #376

2023-02-04 04:29 UTC, jimbxb commented
Oops. Gotta stop doing that

2023-02-04 04:31 UTC, jimbxb commented
My E key is almost broken. Some Es are missing from commit messages :)

2023-02-06 04:45 UTC, pschachte requested changes

2023-02-06 04:45 UTC, pschachte commented on src/Expansion.hs
> +-- | Update the global flows of a parameter, given the
... "given the" what?

2023-02-06 04:45 UTC, pschachte commented on src/Expansion.hs
> +            paramInfoGlobalFlows=flows `globalFlowsIntersection` newFlows}}
Is intersection the right thing here?  A bit of explanation would be helpful.

2023-02-06 04:53 UTC, jimbxb commented on src/BodyBuilder.hs
>                                          -- ^Constraints attached to Boolean vars
Will do.

2023-02-06 04:54 UTC, jimbxb commented on src/BodyBuilder.hs
> +        PrimForeign{} -> do
That's already handled. All outputs take the union of all input's global flows. This handles `move`s and `access`es.

2023-02-06 04:56 UTC, jimbxb commented on src/Expansion.hs
> +-- | Update the global flows of a parameter, given the
Good question. Will finish this off

2023-02-08 09:42 UTC, jimbxb commented on src/Expansion.hs
> +            paramInfoGlobalFlows=flows `globalFlowsIntersection` newFlows}}
I think intersection makes sense here. The global flows assigned initially to each term are as general as possible. We then are able to restrict the globals that *may* be interacted with to some smaller collection. 

One alternative is to just use the value from the map -- in such a case we may add to the global flows of the parameter, and then any analysis that used the old global flows may be invalidated. Same as if we used the union.

There's no way that the global flows should be added to, from what I see. We define the global flows in terms of the resources that are `use`d in the source code, and the only way a different resource could be modified is in a `use` block -- but in a `use` block, the callee never sees these effects, so we can disregard these resources. 

I used the same logic in Optimise.hs when dealing with the inference of global flows originally, using the intersection with the old and the analysed. I should probably document it, if I hadn't already.

2023-05-02 00:23 UTC, pschachte approved these changes

2023-05-02 00:23 UTC, merged

2023-05-02 00:30 UTC, jimbxb commented
Uh oh. I think we need to run an update-exp.