Add JSON parser example
pschachte/wybe pull request #391
Opened 2023-06-02 04:57 UTC by jimbxb

2023-06-09 23:46 UTC, pschachte requested changes
This is really lovely!  Very readable code, and a nice sales pitch for Wybe.  I've made a few style nitpicks here, and also, a bit of documentation would be good for this to be a Wybe code sample.

I agree about using a resource.  It'd make a nice example use of resources, too.

2023-06-09 23:46 UTC, pschachte commented on samples/json.wybe
> +def {test} json(!s:string, ?j:_) {
I suggest being consistent about which argument, first or last, is the string being parsed.  Here it's the first, for `char` it's the last, and in some places it's in the middle.

2023-06-09 23:46 UTC, pschachte commented on samples/json.wybe
> +    [?c | ?rest] = s
How about writing another mode for `char` (where the second argument is output) that does exactly this?  That would make the code simpler and let you avoid a leaky abstraction.

2023-06-10 00:51 UTC, jimbxb commented
Thanks for the feedback though! I've been working on a version with resources that has some different names and some little tweaks to make it ergonomic, but I should add a commit with these changes before tackling the resource version.

Unfortunately, the resource version has uncovered a bad bug that I introduced with HO resources, specifically in the code generation of tests in unbranching and resource transformation. The bug is that, in a test proc, where i save the resources to be reset upon the call failing, I fail to add the tmp variables to the vardicts of nested conditionals -- I do add them to the outer most condional that's generated though. This then results in some tmp variables being "uninitialised" when it comes time to unbranch because they're not known in the vardicts.

The fix should be to just add them, but I think the Haskell code becomes very clunky then, and I'm sure I could do better. The "better" though, is probably a rework of unbranching as a whole, calculating the vardicts when unbranching. I think this is a better design as, if we ever add in more code that generates more tmp variables, then we don't have to worry about updating the vardicts after mode checking. I realise this was done in mode checking because it's convenient, but I think that in unbranching is more appropriate as that's where the data is used.

2023-06-10 00:52 UTC, jimbxb commented on samples/json.wybe
> +pub def {test} (a:_ = b:_) { fail }
This is to fix an annoying bug -- there's no `=` for generic types, so the auto generated `=` here fails in type checking

2024-09-28 14:29 UTC, jimbxb commented on samples/json.wybe
> +def {test} json(!s:string, ?j:_) {
I was trying to follow the order of <inputs> <inouts> <outputs>. No more, now that resources are in place!

2024-09-28 14:30 UTC, jimbxb commented on samples/json.wybe
> +    [?c | ?rest] = s
Event better, I can use an implied mode of this new `char` for the existing one!

2024-09-28 14:34 UTC, jimbxb commented
I finally got back into things...

The parser now "works", but only if I turn off multi-specz. WIth multi-specz on I get a segfault!

2024-09-30 12:25 UTC, jimbxb commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +    wybe.array.[|]<0>(?command##1:wybe.c_string, ?arguments##2:wybe.array(wybe.c_string), ~arguments##0:wybe.array(wybe.c_string), ?tmp#8##0:wybe.bool) #0 @command_line:nn:nn
This is an unfortunate side-effect, but we shouldnt just be mutating a global variable like this! :(

2024-09-30 12:33 UTC, jimbxb commented
Next step, Wybe quines!

2024-09-30 13:50 UTC, jimbxb commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +    wybe.array.[|]<0>(?command##1:wybe.c_string, ?arguments##2:wybe.array(wybe.c_string), ~arguments##0:wybe.array(wybe.c_string), ?tmp#8##0:wybe.bool) #0 @command_line:nn:nn
I suppose we can add a NonAliasedParamCond for globals. That way, if we know the global _isnt_ aliased, a load of the global wouldn't load an aliased value, and we can optimise accordingly. 

This is tricky, as if we ever store into that same global, the alias information changes to whatever the stored value had. 

Recognising that a global is unaliased feels tricky too, but I assume you can just feed in the aliasing information of whatever you store into the global.

Food for thought, but probably not something I'm game to implement.

2024-09-30 13:57 UTC, jimbxb commented on samples/json.wybe
> +    if { parse_item(?x) ::
This should have a !. Not sure why there's no error.

2024-09-30 13:57 UTC, jimbxb commented on samples/json.wybe
> +    !char(?c) & (c = ' ' | c = '\n' | c = '\r' | c = '\t')
Oops. This only handles one whitespace. Need to recurse

2024-09-30 13:57 UTC, jimbxb commented on samples/json.wybe
> +    # this should work...
I do want to fix this. Cons for strings was conflicting with lists

2024-09-30 13:57 UTC, jimbxb commented on samples/json.wybe
> +  | ?len = 1.0
This should be 0.0.

2024-10-01 01:12 UTC, jimbxb commented on samples/json.wybe
> +  | ?len = 1.0
I just need to +1.0 elsewhere

2024-10-02 05:21 UTC, pschachte requested changes
Awesome!  This looks really nice, just the way I hoped a Wybe parser could look.
And thanks for fixing many issues in the compiler.

Just one request:  could you add a header comment to the top of `json.wybe` saying that it's an example of how one might write a recursive-descent parser for JSON documents in Wybe?

2024-10-02 05:21 UTC, pschachte commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +    wybe.array.[|]<0>(?command##1:wybe.c_string, ?arguments##2:wybe.array(wybe.c_string), ~arguments##0:wybe.array(wybe.c_string), ?tmp#8##0:wybe.bool) #0 @command_line:nn:nn
Yes, very tricky.  We need a global analysis to work out that we never either store a potentially aliased value into, and we never alias a value we load from, this global.  Alternatively (or additionally), we need a way to declare that a resource should never be aliased, and always generate code that duplicates the value after loading if it can't be shown that the stored value will not be used again, and before storing if it can't be shown that the stored value is unaliased.  Something like that.  This is a whole other can of worms, certainly not related to a json parser.

2024-10-03 01:40 UTC, pschachte approved these changes
Great; thanks for fixing the Brainfuck doc, too!

2024-10-03 01:40 UTC, merged