Specially handle short strings in the parser
pschachte/wybe pull request #475
Opened 2024-10-21 10:20 UTC by pschachte

These short strings are read using the appropriate constructor, rather than the general buffer
constructor.  So the empty and singleton
constructors are now public.

Other changes include optimising foreign lpvm cast instructions applied to constant chars, integers
and floats, as they get generated in this case.
This avoids several instructions in calling
unboxed constructors with constant arguments.

Also use the -n wybemk flag in final-dump-test.sh, to turn off colourising, making diffs easier to
read.

There are numerous code improvements in final dump tests, including allowing specialisation to kick
in in many places, since unboxed values cannot be
aliased.

There's one unfortunate change in output for
constant_type_constraint_error.wybe: the error
message for ?a = "s":int now complains about a
type error in the call to wybe.string.singleton,
which doesn't appear on the line. I think this is
tolerable for now, as it would be difficult to
fix.

Closes #473

2024-10-21 10:53 UTC, jimbxb requested changes

2024-10-21 10:53 UTC, jimbxb commented on src/Parser.hs
> +termToExp (StringConst pos "" DoubleQuote)
Can this be moved to Normalise? I feel like the parser shouldn't have too much knowledge of the library

2024-10-21 10:53 UTC, jimbxb commented on src/BodyBuilder.hs
> +simplifyOp "fcmp_ord" _ [ArgFloat n1 _, ArgFloat n2 _, output] =
Duplicate of below, should be included with the others anyway

2024-10-21 10:53 UTC, jimbxb commented on src/BodyBuilder.hs
> +simplifyOp "fcmp_ord" _ [ArgFloat n1 _, ArgFloat n2 _, output] =
What does Ord even do?

2024-10-21 10:53 UTC, jimbxb commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +            wybe.string.print<0>[410bae77d3](1187:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #14 @drone:nn:nn
Sweet. This always bothered me a little

2024-10-21 10:53 UTC, jimbxb commented on wybelibs/wybe/string.wybe
> +           | pub singleton(c:char)
Slightly unfortunate we can't have the two pubs together. I want empty (really, all const ctors) first, but buffer needs to be the first non-const.

2024-10-21 10:54 UTC, jimbxb commented on src/Parser.hs
> +termToExp (StringConst pos "" DoubleQuote)
Moving this after type checking (maybe in Clause?) would solve the type error issue, too. But that doesn't make as much sense as in Normalise.

2024-10-21 12:13 UTC, jimbxb commented on wybelibs/wybe/string.wybe
> +           | pub singleton(c:char)
I think a comment why these need to be public is good too. 

I realise the reason why buffer needs to be the first non-const is not clear here, so some elucidation on that would be helpful to pick up now.

2024-10-22 04:57 UTC, pschachte commented on src/BodyBuilder.hs
> +simplifyOp "fcmp_ord" _ [ArgFloat n1 _, ArgFloat n2 _, output] =
fcmp_ord tests that neither value is a NaN.  I've updated WYBE.md to clarify.

2024-10-22 05:03 UTC, pschachte commented on src/Parser.hs
> +termToExp (StringConst pos "" DoubleQuote)
OK, I'll move it to Expansion, after type checking but early enough for the inlining to still work.

2024-10-22 05:37 UTC, merged

2024-10-22 21:24 UTC, jimbxb commented
Sorry for being a bit late to the party, but I'm not sure Expansion is the right place to do this. I believe this string specialisation pass should only ever happen once, as the transformation is idempotent. Expansion may only get ran once at the moment (correct me if I am wrong), but theoretically it could get ran multiple times, so the specialisation pass would be redundant after the first Expansion pass in the module. I realise that we haven't been focusing on making the compiler the most efficient, but I feel we should avoid inefficiencies if we are aware of them.

2024-10-23 00:50 UTC, pschachte commented
Expansion is only run once (not positive there are no circumstances when it is repeated, but I think it's not).  But you're right, we may want to repeat it.  This shouldn't be a problem, though, since after this is done, we don't have the ArgString constructor for empty or singleton strings, so the change is idempotent.  We're already scanning every argument during expansion, to update variables, so looking at ArgStrings and checking them for empty or singleton lists is a minimal added overhead.  And if we moved it somewhere else, it would impose a similar overhead.