Const structs
pschachte/wybe pull request #476
Opened 2024-12-12 05:17 UTC by pschachte

Generate LLVM constant structures in place of code to create structures all of whose contents are constants.  This also applies to constant closures, so the code to optimise them in LLVM generation is now not needed, and to strings of length >1.

2024-12-12 09:59 UTC, jimbxb reviewed
I will get back to the large files that I haven't read in some time. I also need to go through the changes in at least one of the larger exp files in more detail, but they seems sensible!

It's most unfortunate that there's a 100x in the mallocs in the drone test case. I suppose that's harder to get back now that the first drone is static and the compiler isn't smart enough to use a specialisation after that fact :/

2024-12-12 09:59 UTC, jimbxb commented on src/AST.hs
> +constsGlobalFlows fields = return emptyGlobalFlows -- XXX need to recurse!
Is it also possible there are global flows in the other fields? I think it's possible that there is another function pointer nested inside one of the other fields, and I think that should be considered.

2024-12-12 09:59 UTC, jimbxb commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +** malloc count: 100
This is unfortunate.

2024-12-12 11:57 UTC, pschachte commented on test-cases/complex/exp/testcase_multi_specz-drone.exp
> +** malloc count: 100
Very much so.  The two possible fixes I can think of would be to get multiple specialisation working for the recursive call, or to turn the constant back into code to create a fresh structure when that would allow the update to be destructive.  Both of these seem pretty difficult to wrangle, so I put in the PR without fixing this.

2024-12-18 20:23 UTC, jimbxb requested changes

2024-12-18 20:23 UTC, jimbxb commented on src/LLVM.hs
> +    -- XXX is ArgGlobal a constant?  Does it give the address, or value, of the
I think this has come up before. I can't recall exactly what I thought last time, but I think that the address makes sense -- in order to get the value you must `load`.

2024-12-18 20:23 UTC, jimbxb commented on src/AST.hs
> +    specialName2 (showModSpec md) $ "constant" ++ specialChar : show num
We need a `specialName{N}` variant, for N > 2. Seems annoying...

Maybe

```
specialNames :: [String] -> String
specialNames = intercalate [specialChar]
```
is more ergonomic.

2024-12-18 20:23 UTC, jimbxb commented on src/LLVM.hs
> +-- writeConstDeclaration spec@(WybeStringSpec str) n = do
Delete?

2024-12-18 20:23 UTC, jimbxb commented on src/LLVM.hs
> +    -- NB:  this case doesn't seem to ever occur -- probably handled earlier
That's right. The body builder should always first-order-ify these cases. I think I added it a while back, probably before I tackled it in the body builder! Should be safe to remove.

2024-12-18 20:23 UTC, jimbxb commented on src/LLVM.hs
> +typeRep = lift . typeRepresentation
Do we really need this shorthand now?

2024-12-18 20:23 UTC, jimbxb commented on src/LLVM.hs
> +        -- constNames :: Map StaticConstSpec Ident,
Delete?

2024-12-18 20:25 UTC, jimbxb commented on test-cases/execution/nbody.exp
> -5005
Can we update the comment above?

2024-12-20 12:26 UTC, jimbxb commented on src/AST.hs
> +constValueRepresentation (FloatStructMember _ size) = Floating $ size * 8
I recall having constants for these `8`s. Can we use them here too, for clarity?

2024-12-20 12:26 UTC, jimbxb commented on src/AST.hs
> +-- These are defined in Snippets.hs, but we can't import that as it imports AST
Non-recursive modules is painful 😖

2024-12-20 12:26 UTC, jimbxb commented on src/BodyBuilder.hs
> +          Just (CStringInfo str) | len == fromIntegral (length str) -> do
Is there ever a case where this isn't true?

I'm overall not sure why we need this...

2024-12-20 12:50 UTC, jimbxb commented
I'm reviewing this via my phone at the airport, so can't access my laptop. Unfortunately, it seems that after a certain number of files, GitHub refuses to load diffs. I noticed, by chance in one of the commits a change that is odd. This should be the reference to it:

https://github.com/pschachte/wybe/blob/const_structs/test-cases%2Ffinal-dump%2Fearly_error.exp#L74

Any chance we can avoid these changes? I assume the issue is before types, so perhaps in Flatten/Normalise, where string constants are replaced with tmp variables (that hold the constant value). I think this is also causing one of the error messages changing too, that I commented on before.

2024-12-27 04:49 UTC, jimbxb commented on src/Flatten.hs
> +    exp' <- lift $ stringExpr str
I suppose this is what is causing the errors around string constants, as extra "unreachable" statements are introduced. 

I don't know how we can avoid this, unfortunately. Perhaps we can delay this until Clause? That has implications for the const structures that are referenced in the module, I believe.

2025-02-12 04:03 UTC, pschachte commented on src/AST.hs
> +    specialName2 (showModSpec md) $ "constant" ++ specialChar : show num
But specialName puts the special character at the front, while specialName2 puts it between the names.  Either way, only one special character is inserted.

2025-02-12 04:07 UTC, pschachte commented on src/AST.hs
> +            (Fncall ["wybe","string"] "unsafe_cstring_to_string" False
Yeah, I wanted to put "unsafe" in there, since this bypasses the check for length >= 2.  Not that anything terrible would happen now if we used a buffer for a 1 or 0 character string, but it might be useful to be able to count on 0 or 1 characters using the specialised representation.

2025-02-12 04:39 UTC, pschachte commented on src/AST.hs
> +constValueRepresentation (FloatStructMember _ size) = Floating $ size * 8
I can't find any definition of a constant for the number of bits per byte, but I've defined one now.

2025-02-12 04:41 UTC, pschachte commented on src/AST.hs
> +-- These are defined in Snippets.hs, but we can't import that as it imports AST
Yup, really annoying sometimes.

2025-02-12 04:54 UTC, pschachte commented on src/LLVM.hs
> +typeRep = lift . typeRepresentation
We don't need it, but it's used enough to seem worthwhile.

2025-02-12 05:43 UTC, pschachte commented on src/Flatten.hs
> +    exp' <- lift $ stringExpr str
That's right.  Unfortunately, Clause can't handle non-atomic expressions, so it can't turn a string constant into a proc call.  Fixing that would entail merging flattening into LPVM generation, and rewriting the type checker and unbrancher to operate on unflattened code.  That's too big a change.

2025-02-12 05:45 UTC, jimbxb commented on src/Flatten.hs
> +    exp' <- lift $ stringExpr str
Quite unfortunate. I was hoping that clause could at least handle the String constant expressions. I guess I have forgotten how clause works...

2025-02-12 05:52 UTC, jimbxb commented on src/Clause.hs
> -compileArg' typ (StringValue string v) _ = return [ArgString string v typ]
Ah, I see. So the `compileArg'` function has no ability to "emit" an extra prim.

Can't we modify it to allow emission of both a `([PrimArg], [Prim])`, then prepend all the collected `[Prim]` from all args before the resultant `Prim` which uses this Arg? That way, we can omit an extra call to whichever string constructor we required

2025-02-13 01:38 UTC, pschachte commented on src/Clause.hs
> -compileArg' typ (StringValue string v) _ = return [ArgString string v typ]
That is currently handled by flattening and mode checking (remember, expressions can be outputs, in which case the flattened statement must come after the current statement), so this would be a major architectural change.  I'm working on a better fix, which involves annotating expressions with their untransformed version, so it would fix many other places where we confusingly show transformed code in error messages.  I think the right fix would be to incorporate the source code into the OptPos type, but that would be a major change to the parser.  We'll see what I can come up with.

2025-11-23 09:52 UTC, jimbxb commented on test-cases/final-dump/bug228-type.exp
> +final-dump/bug228-type.wybe:5:2: Type of tmp#0:wybe.string incompatible with ?bar
This is addressed in #507

2025-11-23 09:52 UTC, jimbxb commented
> https://github.com/pschachte/wybe/blob/const_structs/test-cases%2Ffinal-dump%2Fearly_error.exp#L74
> 
> Any chance we can avoid these changes? I assume the issue is before types, so perhaps in Flatten/Normalise, where string constants are replaced with tmp variables (that hold the constant value). I think this is also causing one of the error messages changing too, that I commented on before.

This is addressed in #507

2025-11-26 09:56 UTC, jimbxb approved these changes
I took the liberty of merging in master. All still seems to work!

2025-11-26 10:18 UTC, jimbxb commented on test-cases/final-dump/bug_497.exp
> +    bug_497.call<0>(bug_497.#anon#1<1><3>:(wybe.int, ?wybe.bool), 2:wybe.int, ?tmp#0##0:wybe.bool) #0 @bug_497:nn:nn
This `<3>` seems to be untyped? I wonder if we need it

2026-03-17 06:46 UTC, pschachte reviewed
LGTM

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>    setExpFlowType,
```suggestion
  setExpFlowType, sourceAnnotateExp,
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>    OptPos, Placed(..), place, betterPlace, content, maybePlace, rePlace, unPlace,
```suggestion
  SourceInfo(..), OptPos, Placed(..), place, betterPlace, content,
  maybePlace, rePlace, unPlace,
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>  import Data.Binary (Binary)
```suggestion
import Data.Binary (Binary)
import GHC.Profiling (startProfTimer)


-- |The tokens of the wybe language, each carrying its source position.
data Token = TokFloat Double SourcePos          -- ^A floating point number
              | TokInt Integer SourcePos        -- ^An integer
              | TokString StringDelim String SourcePos
                                                -- ^A string with its delimiter
              | TokChar Char SourcePos          -- ^A character constant
              | TokIdent String SourcePos       -- ^An identifier
              | TokLBracket BracketStyle SourcePos
                                                -- ^Some kind of left bracket
              | TokRBracket BracketStyle SourcePos
                                                -- ^Some kind of right bracket
              | TokComma SourcePos              -- ^A comma
              | TokPeriod SourcePos             -- ^A period (full stop)
              | TokSymbol String SourcePos      -- ^A symbol made up of
                                                --  non-identifier chars
              | TokSeparator Bool SourcePos     -- ^A statement separator
                                                -- indicating whether explicit
              | TokError String SourcePos       -- ^A lexical error
    deriving (Eq, Ord, Generic)

-- |The different string delimiters.
data StringDelim = DoubleQuote
                 | BackQuote
                 | LongQuote String
                 | IdentQuote String StringDelim
               deriving (Eq, Ord, Generic)


-- |The different kinds of brackets.
data BracketStyle = Paren | Bracket | Brace
                  deriving (Eq, Ord, Generic)

```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +    cStringExpr $ maybe "Unknown file" (takeBaseName . sourceName) (place pstmt)
```suggestion
    cStringExpr $ maybe "**UNKNOWN FILE**" (takeBaseName . sourceName) (realPlace pstmt)
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +    cStringExpr $ maybe "Unknown file" sourceName (place pstmt)
```suggestion
    cStringExpr $ maybe "**UNKNOWN FILE**" sourceName (realPlace pstmt)
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +    return $ Typed (IntValue $ fromIntegral $ maybe 0 sourceLine (place pstmt))
```suggestion
    return $ Typed (IntValue $ fromIntegral $ maybe 0 sourceLine (realPlace pstmt))
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +    return $ Typed (IntValue $ fromIntegral $ maybe 0 sourceColumn (place pstmt))
```suggestion
    return $ Typed (IntValue $ fromIntegral $ maybe 0 sourceColumn (realPlace pstmt))
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +    cStringExpr $ maybe "unknown location" (showSourcePos full) (place pstmt)
```suggestion
    cStringExpr $ maybe "unknown location" (showSourcePos full) (realPlace pstmt)
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>        | Global GlobalInfo
```suggestion
      | Global GlobalInfo
      | TransformedFrom Exp Exp -- ^A transformed Exp, together with the
                                -- original version, for error messages.
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>  expOutputs (Typed expr _ _) = expOutputs expr
```suggestion
expOutputs (Typed expr _ _) = expOutputs expr
expOutputs (TransformedFrom expr _) = expOutputs expr
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
>  expInputs (Typed expr _ _) = expInputs expr
```suggestion
expInputs (Typed expr _ _) = expInputs expr
expInputs (TransformedFrom expr _) = expInputs expr
```

2026-03-17 06:46 UTC, pschachte commented on src/Flatten.hs
> +    flattenExp exp' ty castFrom pos
```suggestion
    exp'  <- lift $ stringExpr str
    exp'' <- flattenExp exp' ty castFrom pos
    return $ sourceAnnotateExp exp'' expr
```

2026-03-17 06:46 UTC, pschachte commented on src/Flatten.hs
>      flattenExp exp ty castFrom pos
```suggestion
    flattenExp exp ty castFrom pos
flattenExp (TransformedFrom exp src) ty castFrom pos = do
    exp' <- flattenExp exp ty castFrom pos
    return $ maybePlace (sourceAnnotateExp exp' src) pos
```

2026-03-17 06:46 UTC, pschachte commented on src/AST.hs
> +constsGlobalFlows fields = return emptyGlobalFlows -- XXX need to recurse!
Can you explain what you mean?  I confess I don't fully understand global flows and where they might be hiding.

2026-03-17 06:46 UTC, pschachte commented on src/BodyBuilder.hs
> +          Just (CStringInfo str) | len == fromIntegral (length str) -> do
It's been so long I can't remember, but from the fn doc it looks like I was leaving the door open to handle other library types, or for us to change the string type.

2026-03-17 06:46 UTC, pschachte commented on test-cases/final-dump/bug228-type.exp
> +final-dump/bug228-type.wybe:5:2: Type of tmp#0:wybe.string incompatible with ?bar
Yes, it is, but it's hard to fix because flattening loses the original code.  This causes lots of poor error messages.  But I'd like to tolerate this for now and fix it in a later pull.

2026-03-17 06:56 UTC, jimbxb commented
Seems a bunch of comments were just added. If I find some time to go through them I shall, but it would be great if you could see if they're still needed @pschachte

2026-03-17 11:15 UTC, pschachte commented
Yeah, sorry, I'm trying to wrap up this PR, and have gotten stuck trying to deal with all the clashes merging master back into this branch.  It's painful when a branch falls far behind.

2026-03-31 12:20 UTC, jimbxb commented
I suspect there's a missing prescan step in the LLVM generation, where nested constants aren't being added as globals. There's probably a recursion on a primarg that is missed.

2026-04-01 12:40 UTC, merged